//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MmosCourseProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public int AuthorId { get; set; }
        public int TaskId { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> SentDateTime { get; set; }
    
        public User Author { get; set; }
        public Task Task { get; set; }
    }
}
