//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MmosCourseProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskInfoView
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CreatorId { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public int TeamId { get; set; }
        public int State { get; set; }
        public int Priority { get; set; }
        public bool IsUrgent { get; set; }
        public Nullable<System.DateTime> LastChangeDateTime { get; set; }
        public Nullable<int> ParentTaskId { get; set; }
        public int ResponsibleId { get; set; }
        public Nullable<int> SubtasksCount { get; set; }
        public Nullable<int> TotalExecutorsCount { get; set; }
        public Nullable<int> DirectExecutorsCount { get; set; }
        public Nullable<System.DateTime> WholeTaskTreeLastChangeDateTime { get; set; }
    }
}
