//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MmosCourseProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamInfoView
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int TeamLeadId { get; set; }
        public Nullable<int> ParentTeamId { get; set; }
        public Nullable<int> TotalPeopleCount { get; set; }
        public Nullable<int> SuperiorsCount { get; set; }
        public Nullable<int> SubteamsCount { get; set; }
        public Nullable<int> TotalTasksCount { get; set; }
        public Nullable<int> NewTasksCount { get; set; }
        public Nullable<int> TasksInProgressCount { get; set; }
        public Nullable<int> DoneTasksCount { get; set; }
        public Nullable<int> ApprovedTasksCount { get; set; }
        public Nullable<int> TasksWithBugsCount { get; set; }
        public Nullable<int> DebuggingTasksCount { get; set; }
        public Nullable<int> HighestPriorityTasksCount { get; set; }
        public Nullable<System.DateTime> FirstActivityDateTime { get; set; }
        public Nullable<System.DateTime> LastActivityDateTime { get; set; }
    }
}
